# Generated by Django 3.2 on 2021-04-24 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_allergy_allergy_drink_images_nutritions_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='nutrition_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.nutritions'),
        ),
    ]
